name: 'Auto Increment Tag Action'
description: 'Automatically create and push release tags based on branch names with incremental versioning'
author: 'Eric Marchand'

branding:
  icon: 'tag'
  color: 'blue'

inputs:
  branch:
    description: 'Branch to create tag for (leave empty for current branch)'
    required: false
    default: ''
  tag_prefix:
    description: 'Tag prefix to use instead of branch name (leave empty to use branch name)'
    required: false
    default: ''
  tag_suffix:
    description: 'Tag suffix to use.'
    required: false
    default: ''
  git_user_name:
    description: 'Git user name for commits (default: github-actions[bot])'
    required: false
    default: 'github-actions[bot]'
  git_user_email:
    description: 'Git user email for commits (default: github-actions[bot]@users.noreply.github.com)'
    required: false
    default: 'github-actions[bot]@users.noreply.github.com'
  github_token:
    description: 'GitHub token with contents:write permission'
    required: true
  generate_release_notes:
    description: 'Generate release notes with commits when a new tag is created'
    required: false
    default: 'false'

outputs:
  tag:
    description: 'The tag that was created or found'
    value: ${{ steps.create-tag.outputs.tag }}
  tag_commit:
    description: 'The commit hash of the current tag'
    value: ${{ steps.create-tag.outputs.tag_commit }}
  previous_tag:
    description: 'The previous tag before the current one'
    value: ${{ steps.create-tag.outputs.previous_tag }}
  previous_tag_commit:
    description: 'The commit hash of the previous tag'
    value: ${{ steps.create-tag.outputs.previous_tag_commit }}
  tag_created:
    description: 'Whether a new tag was created (true) or an existing tag was used (false)'
    value: ${{ steps.create-tag.outputs.tag_created }}
  release_notes:
    description: 'Generated release notes with commits (when generate_release_notes is true)'
    value: ${{ steps.release_notes.outputs.notes }}

runs:
  using: 'composite'
  steps:
    - name: Setup Git
      shell: bash
      run: |
        git config --global user.name "${{ inputs.git_user_name }}"
        git config --global user.email "${{ inputs.git_user_email }}"

    - name: Create and push tag
      id: create-tag
      shell: bash
      run: |
        "${{ github.action_path }}/create-tag.sh" \
          --branch "${{ inputs.branch }}" \
          --tag-prefix "${{ inputs.tag_prefix }}" \
          --tag-suffix "${{ inputs.tag_suffix }}" \
          --git-dir "${{ github.workspace }}" \
          --github-token "${{ inputs.github_token }}" \
          --output-file "$GITHUB_OUTPUT" \
          --summary-file "$GITHUB_STEP_SUMMARY"
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: Generate release notes
      if: ${{ inputs.generate_release_notes == 'true' && steps.create-tag.outputs.tag_created == 'true' }}
      id: release_notes
      shell: bash
      run: |
        "${{ github.action_path }}/generate-release-notes.sh" \
          --tag "${{ steps.create-tag.outputs.tag }}" \
          --previous-tag "${{ steps.create-tag.outputs.previous_tag }}" \
          --repository "${{ github.repository }}" \
          --output-file "$GITHUB_OUTPUT"
